### ISSUE TITLE
movement-controls broken with Chrome version 97

### ISSUE THREAD

**Issue by Turtleted21** [c-frame/aframe-extras#371] opened 2022-01-24 12:08 UTC
Hi,
movement-controls broken with Chrome version 97, even with aframe 1.1.0
position is not set (always 0 0 0) and mouse is locked
work on Safari, Firefox and Edge

Thanks

**Comment by eviltik** [comment] 2022-02-08 18:53
Thank you for feedback @Turtleted21, can you provide a glitch please ? Perhaps i can help.

**Comment by Turtleted21** [comment] 2022-02-14 10:31
I try to reproduce my bug with Glitch without succes.
In my project bug appear when I have to many entity, with less  entity it work.
It appear only with  Chrome version 97

**Comment by vincentfretin** [comment] 2022-12-04 08:41
This seems to be an issue only on your project. I'm closing the issue. Please reopen if you reproduce your issue on a glitch example.

**Closed as completed by vincentfretin** 2022-12-04 08:41 UTC
